# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(348, 447)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.slider_channel = QtWidgets.QSlider(parent=self.centralwidget)
        self.slider_channel.setGeometry(QtCore.QRect(50, 180, 22, 160))
        self.slider_channel.setMaximum(5)
        self.slider_channel.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.slider_channel.setObjectName("slider_channel")
        self.slider_volume = QtWidgets.QSlider(parent=self.centralwidget)
        self.slider_volume.setGeometry(QtCore.QRect(270, 180, 22, 160))
        self.slider_volume.setMaximum(5)
        self.slider_volume.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.slider_volume.setObjectName("slider_volume")
        self.button_0 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_0.setGeometry(QtCore.QRect(120, 210, 31, 28))
        self.button_0.setObjectName("button_0")
        self.button_1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_1.setGeometry(QtCore.QRect(200, 210, 31, 28))
        self.button_1.setObjectName("button_1")
        self.button_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_3.setGeometry(QtCore.QRect(200, 270, 31, 28))
        self.button_3.setObjectName("button_3")
        self.button_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_2.setGeometry(QtCore.QRect(120, 270, 31, 28))
        self.button_2.setObjectName("button_2")
        self.button_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_4.setGeometry(QtCore.QRect(120, 330, 31, 28))
        self.button_4.setObjectName("button_4")
        self.button_5 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_5.setGeometry(QtCore.QRect(200, 330, 31, 28))
        self.button_5.setObjectName("button_5")
        self.image_channel = QtWidgets.QGraphicsView(parent=self.centralwidget)
        self.image_channel.setGeometry(QtCore.QRect(110, 20, 141, 121))
        self.image_channel.setObjectName("image_channel")
        self.label_channel_buttons = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_channel_buttons.setGeometry(QtCore.QRect(150, 180, 91, 16))
        self.label_channel_buttons.setObjectName("label_channel_buttons")
        self.label_volume_slider = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_volume_slider.setGeometry(QtCore.QRect(260, 160, 91, 16))
        self.label_volume_slider.setObjectName("label_volume_slider")
        self.label_channel_slider = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_channel_slider.setGeometry(QtCore.QRect(30, 160, 91, 16))
        self.label_channel_slider.setObjectName("label_channel_slider")
        self.radioButton = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(270, 350, 95, 20))
        self.radioButton.setObjectName("radioButton")
        self.button_power = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_power.setGeometry(QtCore.QRect(20, 10, 51, 41))
        self.button_power.setObjectName("button_power")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 348, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Project 1"))
        self.button_0.setText(_translate("MainWindow", "0"))
        self.button_1.setText(_translate("MainWindow", "1"))
        self.button_3.setText(_translate("MainWindow", "3"))
        self.button_2.setText(_translate("MainWindow", "2"))
        self.button_4.setText(_translate("MainWindow", "4"))
        self.button_5.setText(_translate("MainWindow", "5"))
        self.label_channel_buttons.setText(_translate("MainWindow", "CHANNELS"))
        self.label_volume_slider.setText(_translate("MainWindow", "VOLUME"))
        self.label_channel_slider.setText(_translate("MainWindow", "CHANNEL"))
        self.radioButton.setText(_translate("MainWindow", "MUTE"))
        self.button_power.setText(_translate("MainWindow", "ON/OFF"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
